### ISSUE TITLE
[Suggestion]Cloning Tab

### ISSUE THREAD

**Issue by timegivenzero** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#10]
To be able to clone one of the ips to like a test server in the same machine obviously. like ip 252 to 255 would be nice

**Comment by timegivenzero** [comment]
everything inside the first server to the second. so i dont have to download my entire server and move it over 10 files at a time

**Comment by ertug2** [comment]
That is something that you should contact us for us to do for you. That's not something that we would specifically add to the control panel at least not at this time.
