### ISSUE TITLE
Server names incorrect

### ISSUE THREAD

**Issue by TWGunman** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#11]
I have noticed recently that not just my server (Tamewater Clonewars RP) but other servers are having a problem that the server name in the browser would be a random mix of numbers and letters instead of the proper name set in the panel config. Is this an isolated instance or is this a well-known issue by now?

Thanks in advance,

Gunman

**Comment by ertug2** [comment]
Hello TWGunman,

As far as I'm aware, that issue can only be caused by one of your server add-ons. My guess is that it's DRM related. There is no other way that the "hostname" variable can be set to anything else on your server. 

It is not panel related as far as I'm aware.

**Comment by TWGunman** [comment]
Hey Ertug,

In that case, I will contact Secure GMOD then as that is the only DRM that I know of is on my server currently. Thank you for the fast response!

Gunman
