### ISSUE TITLE
Text Size - Fullscreen Web Console

### ISSUE THREAD

**Issue by colemclaren** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#12]
The text size is too large in full screen, keeping minorities and women out of programming.

**Comment by ertug2** [comment]
Is this change good?:

![1](https://cdn.gmchosting.com/SIHNz.png)

**Comment by colemclaren** [comment]
Yes, that is very good.

**Comment by ertug2** [comment]
Alright, it will be released on the next panel revision.
