### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by SaintofDiablo** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#14]
if a server crashes , their should be a tab that saves that last x amount of lines spit from the console so it helps server owners figure out what caused a crash . Would be quite useful .

**Comment by ertug2** [comment]
The panel already saves every single server stop and or crash console.log file to: /serverip_port/gmcpanel-crash-logs/. It saves the full log and tags it by date/time/type.

**Comment by ertug2** [comment]
Let me know if you believe that, that isn't sufficient enough. 

It should be more than enough since it orders it properly and gives you the full and raw log.
