### ISSUE TITLE
Server issue 

### ISSUE THREAD

**Issue by SaintofDiablo** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#16]
Every morning , my server when it auto restarts , it dupes it self with a different port , this issue has been going on for awhile now .

**Comment by ertug2** [comment]
I do apologize for the delay. 

I have noted the issue and will look further into it. I thought that I resolved it a while back but it still seems to appear randomly.

**Comment by ertug2** [comment]
Do you know if it actually happens every single morning or if it is more of an erratic thing?

**Comment by SaintofDiablo** [comment]
It happens randomly . Like this morning it sent me an email saying the server 'crashed' and then they were 2

**Comment by SaintofDiablo** [comment]
Issue still persists

**Comment by ertug2** [comment]
Not a problem, I understand that it is still persisting. 

Just to confirm, when you restart your server, does it ever go into the "not responding" mode before it fully boots up and is able to be joined?
