### ISSUE TITLE
Console will not work

### ISSUE THREAD

**Issue by AzaPattaz** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#18]
The console will not send any commands I input to the server. This happens even after server restarts. My server only contains addons downloaded through addon manager so nothing should conflict

**Comment by AzaPattaz** [comment]
If I try to use rcon in game, it gives me this error `Unable to connect to remote server (51.254.51.2:27015)
`

**Comment by ertug2** [comment]
That issue is directly related to your server configuration. You most likely entered your rcon password into the server.cfg file instead of using our button. Feel free to reopen this if that is not the case. Thanks.
