### ISSUE TITLE
Unable to install CS:S into my server

### ISSUE THREAD

**Issue by AzaPattaz** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#19]
Installing CS:S through the addon manager results in the install window briefly appearing before the webpage reloads to still show that the install button is still present.
![image](https://user-images.githubusercontent.com/19674707/36342665-894b3bf8-13f9-11e8-9669-669b2241a0a6.png)
![image](https://user-images.githubusercontent.com/19674707/36342670-91a3ae8e-13f9-11e8-9701-289563a0f881.png)
![image](https://user-images.githubusercontent.com/19674707/36342673-9803497e-13f9-11e8-8916-24cb37c428d1.png)

**Comment by ertug2** [comment]
That is a known bug from when we adapted other games to our custom control panel. CS:S is installed by default but it will show it as being not installed in the addon manager. I have tagged it as a bug. Thanks.

**Comment by ertug2** [comment]
It should show CS:S content as properly installed by default now.
