### ISSUE TITLE
Prometheus unable to connect to MySQL database?

### ISSUE THREAD

**Issue by peter-r-g** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#2]
This problem appears in the server console every couple minutes and we have been unable to get this problem fixed.

Error Message:
[Prometheus repeated error of 21:37:39 - 26/06/2017] DB Connection failed! Error msg: Unknown MySQL server host 'web-panel01.gmchosting.com' (111)

**Comment by ertug2** [comment]
Hello Gunman,

I am looking into the issue now. That was indeed what I was looking for.

**Comment by gunman435** [comment]
Is this what you are looking for?
https://lgg.managed.gmchosting.com/dashboard/game/servers/3/

**Comment by peter-r-g** [comment]
Where should I send this to you? I don't use github that often sorry

**Comment by ertug2** [comment]
We already have what we needed from your previous response.

**Comment by peter-r-g** [comment]
Oh alright then

**Comment by ertug2** [comment]
Unfortunately, we weren't able to reproduce the issue on our end. What you're experiencing on your end appears to be an isolated situation. I would recommend that you contact the account holder and get them to contact us from there if they need to. 

This is more for bugs that affect everybody globally and not for specific and isolated issues.

**Comment by peter-r-g** [comment]
Okay, thank you for trying to help!
