### ISSUE TITLE
branch changing for steam updater

### ISSUE THREAD

**Issue by meepen** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#22]

**Comment by ertug2** [comment]
I will be looking into supporting automatic steam updating in a near update. 

I'll also look into adding the option to specify what branch you want to update your server onto. I don't know if supporting automatic steam updating for a different branch would even be worth it though so I'll look into that as well.

**Comment by ertug2** [comment]
The control panel update has been released which includes the option to change the branch. Let me know if you have any further inquiries.
