### ISSUE TITLE
Mounting CSS in Addon Manager doesn't update properly.

### ISSUE THREAD

**Issue by craighulme** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#23]
If you mount CS:S and then reinstall the server then CS:S still appears mounted when its not, to fix I had to swap my mount.cfg with another server that has CS:S mounted with gmc. Maybe check to see if CSS is actually mounted on every server boot?

**Comment by ertug2** [comment]
Sorry about the delay.

The base mount.cfg file is always copied onto the server on install/reinstall. It is a common issue for clients to overwrite it by accident. 

The issue with forcefully writing on server start is that some clients have custom entries in their mount.cfg file with our existing entries above it. That would break their additions fully. It's best for new customers to make sure to not override our existing mount.cfg file when uploading their server files. The CS:S entry in the addon manager is supposed to be more of a blind on/off switch unlike the other entries in the addon manager.
