### ISSUE TITLE
Suggestion: Enable Auth for gitcloning for private projects

### ISSUE THREAD

**Issue by craighulme** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#24]
Would be nice

**Comment by ertug2** [comment]
Do you mean such as supporting SSH keys? I wanted to make sure to not complicate the button more than it had to be. 

I was hoping that some clients who wanted to do private repositories would do a IP white-list to make a public repository "private" that way. From what I understand though, no public git company really supports that feature, they only support SSH keys.

You could technically use a company which offers automatic GIT to FTP transfers as a workaround.

**Comment by Kill-Zone** [comment]
@CraigHulme This is possible using deployment tokens via GitLab, should also work with OAuth too.
Please see https://docs.google.com/document/d/1ji5a9wn7rhexNF0y-fySMFL2il9-YQXpBcSKOXTvznM
for instructions on how to do that, the URL format will be the same.

Think that's the issue fixed, can close

**Comment by ertug2** [comment]
Closing this out since it appears to be resolved.
