### ISSUE TITLE
Suggestion: Add submodule suppot to Git Cloner

### ISSUE THREAD

**Issue by Kill-Zone** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#25]
Okay, so at the moment, it's possible to clone git repositories. However due to the nature of Git, any submodules inside the parent repo won't be cloned. The way that you would bypass this is by running a slightly modified git clone command when you want to clone the repository, including it's sub-repositories (submodules)
>git clone --recurse-submodules -j8 git@gitlab.com:my-dev-team/repo.git (HTTPS also works afaik)

So the feature request is either adding custom clone parameters or allow users to specify the entire git command.

Thanks for reading!

**Comment by ertug2** [comment]
I went ahead and defaulted it to do "--recurse-submodules". 

Would that work for you?

**Comment by Kill-Zone** [comment]
( Think i already anwsered this to you on discord but i will forward it
here aswell )

Yes, it would :) !

Thanks!

**Comment by ertug2** [comment]
Yes, I just wanted to make sure that we followed up here so that I could mark it as closed.

I have made the adjustment and will push the update soon.
