### ISSUE TITLE
Workshop.lua file - Suggestion

### ISSUE THREAD

**Issue by iktray** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#26]
It will be great if we can know the name of the workshop item name instead of searching up the ids.

**Comment by ertug2** [comment]
As per your request, I have tweaked it so that whenever you download anything using the tool, it tags the name of the workshop addon then the appropriate ID after it.

Once this panel update is released, you will see the change.

**Comment by ertug2** [comment]
It has been pushed.
