### ISSUE TITLE
Issues connecting to panel

### ISSUE THREAD

**Issue by frostydev99** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#29]
To connect to my panel, I must type in cp-dal05.gmchosting.com and then delete the 05.  Afterwards it lets me login, my friend was given cp-dal.gmchosting.com as the link we needed to login to.

**Comment by ertug2** [comment]
That is a caching issue with your browser. It should work fine once you clear your cookies.

There isn't much that can be done about client-side caching issues.
