### ISSUE TITLE
Server restart button [BUG]

### ISSUE THREAD

**Issue by Corvezeo** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#3]
What's your issue>?
At times the restart button will break and not work fully as intended. it will stop the service and close out the menu, it doesn't fully reboot the server. 

How can you reproduce the error? 
Click on the restart server button and watch it break.

**Comment by ertug2** [comment]
I will take a look at it in the morning and will get back to you then.

**Comment by ertug2** [comment]
I have made slight adjustments to the restart system. Let me know if the issue reoccurs.

**Comment by ertug2** [comment]
As far as I'm aware, the issue is fully resolved. If it reoccurs, feel free to reopen the issue. Thanks.

**Comment by VaasKahnGrim** [comment]
wow, kinda disrespectful title there corv. reminds me of how you treated your players when you had them

**Comment by Corvezeo** [comment]
@cactusadmin Rekt.

**Comment by ertug2** [comment]
I would ask that you keep stupid drama out of this. Unless you have a problem with our control panel, please don't respond. Thanks.
