### ISSUE TITLE
BUG: Workshop Downloader Error[25]

### ISSUE THREAD

**Issue by Yaldabaoth0** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#31]
While trying to use the workshop downloader for the last three hours, It will randomly stop and read "Error [25]  An unknown error has occurred while trying to download your requested workshop addon/collection. Please try again later."

**Comment by ertug2** [comment]
We are aware of Valve rate-limiting our requests. You will have to keep trying until it works. 

There isn't much that we can do from our side.

**Comment by Yaldabaoth0** [comment]
Thanks!
