### ISSUE TITLE
Add a new group: Super User

### ISSUE THREAD

**Issue by ReckerXF** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#34]
Hello,

I am suggesting that you make groups for the panel to improve user experience:

- Admin (Owner of the server)
- Super User (Can be assigned permissions such as paying invoices directly, opening support tickets, and adding new subusers).
- User/Sub User (Self Explanatory)

I think this would be much easier for communities that have multiple personnel in leadership positions - they could simply add them to Super User!

~ Blizzard

**Comment by ertug2** [comment]
Is this for the game panel or billing/client area?

**Comment by ReckerXF** [comment]
Game Panel, although I do think it'd be nice to include billing users who can pay invoices, etc. too 🤔

**Comment by ertug2** [comment]
The game panel doesn't have invoices or support tickets. 

The game panel is the absolute last place that you should give people access. While not a bad idea, it's designed to be an account holder to sub-user system to keep simplicity and not have to worry about sub-sub user issues.

**Comment by ReckerXF** [comment]
That's understandable - I just thought it'd be easier for large communities that have multiple servers, etc.

**Comment by ertug2** [comment]
No worries. I'll close this out since it would only complicate some tasks.
