### ISSUE TITLE
Workshop Downloader broke

### ISSUE THREAD

**Issue by NotReiken** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#37]
So, I was trying to download some new maps into our server, and when I loaded in, the maps weren't there. Neither were new models that were downloaded earlier. My team believes this to be caused by the newest Steam Workshop update that allows Garry's Mod workshop items to be 2.1 gigabytes in size. Any and all help would be appreciated, as our server requires constant updates, and with these addons blocked, I have to manually add each and every new addon into the folder that isn't compatible with the Workshop Downloader.

**Comment by ertug2** [comment]
The issue was indeed the Garry's Mod workshop update.

The new panel update is out which now allows our workshop downloader to support UGC related content. 

Test the workshop downloader if you could please.
