### ISSUE TITLE
Error that none of us can figure out.

### ISSUE THREAD

**Issue by NotReiken** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#38]
So, I was installing WiltOS ALCS to our server. I restarted it after installing, and got this error
"Couldn't load shader dll: game_shader_generic_garrysmod_srv.so". It doesn't show anything beforehand.  I've already tried removing everything WiltOS related, and I now have no idea what is causing the error. The server won't even start cause of it. From the research I've done, apparently its related to Linux.

**Comment by ertug2** [comment]
This is for panel related bugs, not issues related to you missing core files.

Simply do a steam update on your server and it should work as expected.
