### ISSUE TITLE
Add IP to the /getinfo API

### ISSUE THREAD

**Issue by colemclaren** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#39]
Can we please get the connection information added to the /getinfo api of servers, please? It has serv_name already, but there's no server ip or server port connection information attached to the id.

**Comment by ertug2** [comment]
Sorry for the late response, been quite swamped as of late.

I added the two fields: server_ipv4_address and server_gameport.

The panel update adding this will be out globally in an hour. I will comment back here when it's out.

**Comment by ertug2** [comment]
It is now live.

Let me know if that does what you wanted.
