### ISSUE TITLE
Bug with wep console

### ISSUE THREAD

**Issue by Minisoft321** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#4]
When i try to execute a console command through wep console
like fx ("wire_expression2_reload") the console dont register it and execute
it don't do anythinge.

**Comment by ertug2** [comment]
There is a known SRCDS issue where the application does not accept the appropriate RCon password. My recommendation is that you try changing your RCon password something random such as: "hay15sasf" then try restarting your server and see if the issue still occurs. It's more of an issue with SRCDS and not our control panel as far as I'm aware.
