### ISSUE TITLE
IP Whitelisting for FTP Refusing Connection

### ISSUE THREAD

**Issue by Skeptic12** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#40]
Hello, I've tried to set the IP white-list up for my FTP but it's continuing to refuse me access. 

Using the same machine and network as the IP whitelisted, I get this error:

_Response:	530 Wrong ip detected - your account has ip whitelisting enabled, however, your current ip address doesn't match what we have in our system...
Error:	Critical error: Could not connect to server_

**Comment by ertug2** [comment]
I have made adjustments and confirmed that it fixed the issue.

I have specifically pushed it to your panel for the moment. It will go out globally in the near future.

**Comment by ertug2** [comment]
Panel update pushing this change globally is now live.
