### ISSUE TITLE
"Tried to look up command thirdperson as if it were a variable." SPAM

### ISSUE THREAD

**Issue by unbold** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#41]
This is spammed in my Garry's Mod's "~" console, "Tried to look up command thirdperson as if it were a variable."

Only spammed in my Garry'sMod "~" console when I activate my thirdperson addon.
My thirdperson addon i use: https://www.gmodstore.com/market/view/25

Happens ONLY (from what I've tested) when I have this enabled: 
![Untitled](https://user-images.githubusercontent.com/30318124/79642720-0b987c00-8154-11ea-823b-062904f17b2c.png)

**Comment by ertug2** [comment]
Is that in your client or server console?

**Comment by Noahbg** [comment]
This is a client issue just add this to your autoexec

con_filter_enable "1"
con_filter_text_out "Tried to look up command thirdperson as if it were a variable."
