### ISSUE TITLE
Allow TS Management/Query via TS3 Toolkit app

### ISSUE THREAD

**Issue by kristensoils** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#43]
It would be very handy to allow TS management and queries via apps like TS3 Toolkit app on Android. I often use the server, though always on mobile and logging in to manage through the web interface takes a long time and is a bit cumbersome while in the midst of a game. {{ Enhancement Request }}

**Comment by ertug2** [comment]
While this is very old, we can still open up server query manually for you so that you can control the server. Feel free to open a ticket if this is still relevant.
