### ISSUE TITLE
Cant add owner of another server as a subuser on my server.

### ISSUE THREAD

**Issue by zeocrash** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#44]
My friend and I both have Gmod servers with GMC hosting.
I tried to make him a subuser on my GMod server and was told that i couldn't because his email address was already in use.
I currently have no subusers on my GMod server so i assume the email address conflict is arising because his email address is in use as the admin account for his server.
Is it possible to either create a subuser account for his email address on my server or assign subuser privileges to his existing account so that he can access my server as well as his from a single login.

**Comment by ertug2** [comment]
Please open a ticket for this on our site, this is not the right place for it.
