### ISSUE TITLE
Server won't stop Reinstalling

### ISSUE THREAD

**Issue by ZBate** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#49]
Last night me and my friend were trying to get my server up when we ran into a couple of problems. The first being the config files were missing, followed with CS: Source not being mounted upon entering the game. So at an attempt to see if it would fix the issue, we decided to reinstall the server. It has been reinstalling for about 12 hours now, is there any way to fix any of these issues? Thank you.

**Comment by ertug2** [comment]
This isn't a place to reach out for general support, open a ticket for that.
