### ISSUE TITLE
Conflicting Ports

### ISSUE THREAD

**Issue by chaoticcove** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#52]
My Connection Info is showing a different port than what the servers actual port is.

--Connection info according to GMCPanel--
Connection Info: 208.103.169.70:27021

--Console Log--
WARNING: Port 27021 was unavailable - bound to port 27022 instead
WARNING: Port 28005 was unavailable - bound to port 28013 instead
Network: IP 208.103.169.70, mode MP, dedicated Yes, ports 27022 SV / 28013 CL

This is looks to be due to a server having/sharing a port with us, as I just got the server.

**Comment by ertug2** [comment]
Please open a ticket for this on our site, this is not the right place for it.

**Comment by chaoticcove** [comment]
my bad I have no idea how I ended up there in my sleep deprived work, thank
you.
