### ISSUE TITLE
Bug: GMod Store Addons Placed in my Addons Folder are Not Working

### ISSUE THREAD

**Issue by Wizard0fOzzy** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#54]
Two Gmod Store Addons, the Cuffs & New Perspective ones, are failing to load into my server.  Below will be a link to a picture of console after a reset. Nothing seems to be causing errors but they don't load. It's especially odd as other addons I have dragged into my addons folder via FTP are working.

SCREENSHOT: https://imgur.com/a/7wnZHRC

**Comment by ertug2** [comment]
This is a addon specific issue. Open a ticket for this as it's not likely a general panel problem
