### ISSUE TITLE
Give users access to view *.mdump

### ISSUE THREAD

**Issue by masonticehurst** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#6]
For server owners that actually know what they're doing, having mdump files greatly helps to investigate the stack traces that are the cause of crashes.

It become quite frustrating that these are not accessible. Is there any chance you could add a folder in the root where all *.mdump files are accessible? Or is this not possible on the current Linux distro?

Thanks (:

**Comment by ertug2** [comment]
Unfortunately, Valve stored the mdump files in a very abnormal global directory so it would not be possible for us to allow clients to view it automatically. 

We usually also do not provide them on request since even with the most skilled clients, they cannot find anything useful from the crash dumps. If you can convince us that the mdump file would actually be beneficial then we can look into it in a support ticket.

**Comment by masonticehurst** [comment]
It is indeed a shame; luckily though, RobotBoy and Willox are active enough on Facepunch to [usually](https://facepunch.com/showthread.php?t=1560743&p=52493153#post52493153) [give](https://facepunch.com/showthread.php?t=1557673&p=52001762&viewfull=1#post52001762) [pointers](https://facepunch.com/showthread.php?t=1560924) on such issues. (Since they are the only ones with the actual source code before the game versions are compiled).

I believe it was also stated that Linux crash dumps contain much more useful information than their Windows counterpart. The dev branch (which very well by now may have had this committed into the main branch) contains some useful text information aswell.

I'm a developer for a roleplay framework that currently uses GMC and to my understanding a support ticket was made, though I don't believe a response has yet been received.

Edit:
To clarify, we've been suffering for an odd crash issue for quite some time (it happens much too often) which appears to be caused by something related to how the net library is receiving some UInt data. Just been trying to get to the bottom of it forever, but without logs this is almost impossible as the console.log doesn't provide any errors or stack traces.

**Comment by ertug2** [comment]
I understand. As far as I'm aware, we have no support ticket unanswered on our end. If they have not responded to it yet then I ask that they do so or make a new one with the account holder.

**Comment by masonticehurst** [comment]
It appears the support ticketing is down, is there any other way to receive them?

**Comment by ertug2** [comment]
Our support ticket system is not and has never been down to my knowledge.

**Comment by masonticehurst** [comment]
"Please keep in mind that we have temporarily closed down our other methods of support until further notice. We will still be available via our normal support tickets and direct support for clients who have it. We plan to bring things back to normality within a couple of weeks to months."

**Comment by ertug2** [comment]
Look right below that: 

Please keep in mind that we have temporarily closed down our other methods of support until further notice. We will still be available via our normal support tickets and direct support for clients who have it. We plan to bring things back to normality within a couple of weeks to months.

1. Support Tickets:
If using our live chat system, email support or phone support isn't for you then you may use our support ticket system for any questions or concerns.


Click here for: Presale Tickets

**Comment by ertug2** [comment]
I would presume that you have found how to open a support ticket to request a dump file. I'm closing this now. Thanks for contacting us.
