### ISSUE TITLE
[Suggestion] Add the possibility to choose the branch of his server

### ISSUE THREAD

**Issue by redmamba75** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#62]
Have the possibility to choose the branch of his server (dev, prerelease, x86-64 and normal)

https://wiki.facepunch.com/gmod/Downloading_a_Dedicated_Server#theexperimentalbranches

**Comment by ertug2** [comment]
You may already pick between some of those branches via the steam updater button on the panel. Do you need the other branches added?

**Comment by redmamba75** [comment]
Yes, it would be cool to be able to choose your server branch directly from the Steam update panel because currently we have no choice but to use the default branch.

**Comment by ertug2** [comment]
It does let you pick between different branches via the tool currently. There’s explicitly a section for it

**Comment by redmamba75** [comment]
That's right, my apologies, I didn't notice that it was a button, the "Advanced Options". I thought it was some sort of title where, in the future, underneath that text, there would be options. 🤦‍♂️
